helper.js
server.js

Created route for all products and Axios get request for all products
Create route for single product and Axios get request for single product
Created route for product styles and Axios get request for product styles for a product
Create route for related products and axios get request for related products
Created route for reviews for a product and axios get request for reviews for product
Created route for review metadata for product and axios get request for review metadata
Created route for posting a review for a product and axios post request for a review
Created route for marking review as helpful and axios put request for marking reviews
Created route for reporting a review and axios put request for reporting reviews

Created Routes for Products and Reviews

---

client/src/components/App.jsx
client/src/context/reviews/ReviewState.js
client/src/context/reviews/reviewContext.js
client/src/context/reviews/reviewReducer.js
client/src/context/types.js
helper.js

Created Reviews folder for Context
Set up Review Context.js
Set up ReviewReducer.js
Set up ReviewState.js
Wrapped components in App with ReviewState

Context setup

---

client/src/components/ProductOverview/ProductOverview.jsx
client/src/components/ProductOverview/product-image-gallery/product-image-gallery.component.jsx
client/src/components/ProductOverview/product-image-gallery/product-image-gallery.styles.scss

Added product image gallery
Succesfully changing images on click
Updated styling to update image gallery

Product overview styling and image gallery update

---

client/src/components/RatingsAndReviews/Reviews/PhotoTiles.jsx
client/src/components/RatingsAndReviews/Reviews/Review.jsx
client/src/components/RatingsAndReviews/Reviews/Sorter.jsx
client/src/components/RelatedItems/Voter.jsx
client/src/components/sharedComponents/StarRating.jsx
client/src/components/sharedComponents/Voter.jsx
client/src/styles/sections/_ratings.scss

added star ratings as a shareable component between widget
s

Added Star ratings component

---

client/src/components/ProductOverview/product-image-gallery/product-image-gallery.component.jsx
client/src/components/ProductOverview/product-image-gallery/product-image-gallery.styles.scss

Created Thumbnail Scroll
Get Height of Thumbnail container using useRef
Set height of thumbnail container with css properties overflow-y and overflow-x hidden to hide scroll bar but enable scroll functionality
Create a function handleLoad that waits till images inside Thumbnail container is fully loaded and then sets the height to the value of the div
Create a handleScroll function that takes in a height parameter which is calculated using the thumbnail container height. If the user clicks the up arrow, it will take half of the height of the thumbnail container and add that to the value in ref.current.scrollTop to move up. vice versa for scrolling down

Thumbnail scroll ![](http://g.recordit.co/8xIIqAU1cp.gif)

---

client/src/components/RatingsAndReviews/RatingsData/Characteristics.jsx
client/src/components/RatingsAndReviews/RatingsData/RatingsData.jsx
client/src/styles/sections/_ratings.scss

Created characteristics scoring meter

---

client/src/components/RatingsAndReviews/RatingsData/Characteristics.jsx
client/src/components/RatingsAndReviews/RatingsData/RatingsData.jsx
client/src/components/RatingsAndReviews/Reviews/ReviewList.jsx
client/src/components/RatingsAndReviews/Reviews/Sorter.jsx
client/src/components/sharedComponents/Voter.jsx

https://user-images.githubusercontent.com/52953412/140239507-3f168638-0c2a-4960-a041-7d6dfe4336f2.mp4

Added Helpfulness/Newest sorting

---

client/src/components/ProductOverview/ProductOverview.jsx

corrected the incorrect file path name in product overview that caused module import error

corrected incorrect file path name

---

client/src/components/RatingsAndReviews/Reviews/ReviewList.jsx

Created simple sorting algo that weighs the date review was created based on the dates of other reviews and adds the helpfulness to create an overal score and sorts the reviews with highest score first.
https://user-images.githubusercontent.com/52953412/140245521-9294e3cd-1314-448a-aac3-56f7b3a0c3b7.mp4

added relevance sorting

---

client/src/components/RatingsAndReviews/Reviews/PhotoModal.jsx
client/src/components/RatingsAndReviews/Reviews/PhotoTiles.jsx
client/src/components/sharedComponents/Modal.jsx
client/src/styles/sections/_ratings.scss

https://user-images.githubusercontent.com/52953412/140407036-309f4cc7-4733-4579-af1b-2ac3e4b4620d.mp4

Created close functionality for modal component

---

client/src/components/RatingsAndReviews/Reviews/ReviewForm.jsx
client/src/components/RatingsAndReviews/Reviews/ReviewList.jsx
client/src/components/sharedComponents/Modal.jsx
client/src/styles/sections/_ratings.scss

added some adjustments for modal close X

---

client/assets/expand.svg
client/src/components/ProductOverview/product-expanded-view/product-expanded-view.component.jsx
client/src/components/ProductOverview/product-expanded-view/product-expanded-view.styles.scss
client/src/components/ProductOverview/product-magnify/product-magnify.component.jsx

http://g.recordit.co/g1rKR9DEuV.gif
Created function within Product Expanded View component to handle zoom
Created a zoom state within handle zoom
Create a figure div element which will be the zoomed imagethat wraps the main image src
When clicking the main image, function will set the opacity of the main image to 0 to disappear only leaving the zoomed image
Handle Zoom function takes the left top width and height values from e.target.getBoundingClientRect();
Use these values to calculate the x and y coordinates of mouse click
Set the zoomed image with the x and y coordinates of the mouse click
Create a zoom scroll function onMouseMove
Will use the x and y coordinates to constantly update the backgroundPosition of the background image
Created an SVG icon that will set the expanded view …

Magnify implementation

---

client/src/components/QuestionsAndAnswers/AnswerForm.jsx
client/src/components/QuestionsAndAnswers/AnswerList.jsx
client/src/components/QuestionsAndAnswers/QuestionForm.jsx
client/src/components/QuestionsAndAnswers/QuestionList.jsx
client/src/styles/abstracts/_colors.scss
client/src/styles/abstracts/_fonts.scss
client/src/styles/base/_containers.scss
client/src/styles/base/_mixins.scss
client/src/styles/components/_buttons.scss
client/src/styles/components/_forms.scss
client/src/styles/sections/_questions.scss

Ticket: [https://trello.com/c/s4ZPqBnm](url)
Implemented the add a button functionality
- Opens a modal window (shared component built by Chris)
- Used formik to compose form
- Used CSS to format and design
- Validates email addresses and maximum characters per field

Implemented the Add a Question Button and Form (no server requests)

---

client/src/components/ProductOverview/ProductOverview.jsx
client/src/components/ProductOverview/ProductOverview.styles.scss
client/src/components/ProductOverview/product-expanded-view/product-expanded-view.styles.scss
client/src/components/ProductOverview/product-star-rating/product-star-rating.component.jsx
client/src/components/RatingsAndReviews/RatingsAndReviews.jsx
client/src/styles/sections/_products.scss

Updated Styling on Product Details
Added scroll behavior when clicking on all reviews

Product overview extra styling and scroll behavior on review button click ![](http://g.recordit.co/yhZhUKrgTA.gif)

---

client/src/components/QuestionsAndAnswers/AnswerItem.jsx
helper.js
server.js

Ticket: [https://trello.com/c/y8KZsk1X](url)
Implemented the helpful answer functionality to update server
- Created an axios post request to server when user clicks on helpful answer link
- Created a request handler to handle the client post request
- Created an axios post request helper function that updates the api server
- Deleted the "markQuestion" function inside the helper.js file because it was not being used

Updated the helpful answer functionality to update server

---

client/src/components/App.jsx
client/src/context/clickTracker/ClickTrackerContext.js
client/src/context/clickTracker/ClickTrackerReducer.js
client/src/context/clickTracker/ClickTrackerState.js
client/src/context/types.js
client/src/index.jsx

Created Click Tracker Context
Created Click Tracker Reducer
Clicked Create Tracker State
Created handle click function within App component that handles clicks on any element within the app component
Handle click function checks if clicked element is an element and if so, dispatches an action that passes the element, classname and timestamp 
Clicked data will be stored in ClickState
Wrapped Main App component in Index.js with ClickTrackerState. This is because I am not able to use the ClickTrackerContext actions where my ClickTracker State lies.

Click Tracker Implementation

---

client/src/components/RatingsAndReviews/Reviews/ReviewForm/FormPhotoViewer.jsx
client/src/components/RatingsAndReviews/Reviews/ReviewForm/PhotoInput.jsx
client/src/components/RatingsAndReviews/Reviews/ReviewForm/ReviewForm.jsx
client/src/components/RatingsAndReviews/Reviews/ReviewForm/StarRater.jsx
client/src/components/RatingsAndReviews/Reviews/ReviewForm/TraitRater.jsx
client/src/styles/sections/_ratings.scss

- Dynamic changing stars on mouse hover
- Tracked stars on click
- photo input
- photo tiles in form
- modal photo view in form
Modal component requires some refactor for className. 
https://user-images.githubusercontent.com/52953412/140573190-dc72b796-e043-40b6-9218-073a421c1161.mp4

Added stars and Photos to form

---

client/src/components/QuestionsAndAnswers/AnswerItem.jsx
client/src/styles/sections/_questions.scss
helper.js
server.js

Ticket: [https://trello.com/c/oEtl2ZQa](url)
Implemented report an answer functionality
- Refactored client axios put request to handle both helfulness and report user actions
- Refactored the doReport button/function to dynamically change from clickable to static, from black to red, from "report" to "reported"
- Added server and helper functions to handle the report an answer functionality
- Verified that the answers are being marked as reported in the api server

Implemented report an answer functionality

---

client/src/components/RatingsAndReviews/Reviews/PhotoTiles.jsx
client/src/components/RatingsAndReviews/Reviews/ReviewForm/FormPhotoViewer.jsx
client/src/components/RatingsAndReviews/Reviews/ReviewList.jsx
client/src/components/sharedComponents/Modal.jsx
client/src/styles/sections/_ratings.scss

add class property to Modal props
allows for individual styles for each modal.

refactored Modal component to take class name

---

client/src/components/RelatedItems/OutfitCard.jsx
client/src/components/RelatedItems/RelatedItemCard.jsx
client/src/context/clickTracker/ClickTrackerState.js
client/src/context/products/ProductState.js

https://trello.com/c/z7KJq2iz
Updated ProductContext to dynamically update base on a related item click
Added an onclick handle to the product-card-container
Added a data attribute to access the product id
Used the context action dispatchers to send this product Id and update the product state with the reducer

Related Item Rerender Product Overview on Click

---

client/src/components/ProductOverview/product-cart-modal/product-cart-modal.component.jsx
client/src/components/ProductOverview/product-cart-modal/product-cart-modal.styles.scss
client/src/components/ProductOverview/product-dropdown/product-dropdown.component.jsx
client/src/components/ProductOverview/product-navbar/product-navbar.component.jsx
client/src/context/cart/CartReducer.js
client/src/context/cart/CartState.js
client/src/context/types.js

Created context action to add cart item details
Displays items added to cart
Created modal for cart

Cart Modal Functionality

---

client/src/components/QuestionsAndAnswers/AnswerForm.jsx
client/src/components/QuestionsAndAnswers/AnswerImgForm.jsx
client/src/components/QuestionsAndAnswers/AnswerList.jsx
client/src/components/QuestionsAndAnswers/QuestionItem.jsx
client/src/components/QuestionsAndAnswers/QuestionList.jsx
client/src/components/sharedComponents/Modal.jsx
client/src/styles/base/_containers.scss
client/src/styles/sections/_questions.scss
helper.js
server.js

Ticket: [https://trello.com/c/FSUrWAxe](url)
Implemented the post a new answer functionality:
- Created post request on answer form to send new answer data to server
- Created a request handler to handle the post request and send it to the helper function
- Created a post request in the helper function that successfully pushes to the api server
Began work on uploading images:
- Created a new modal window for window uploads
- Began working on the upload a photo form

Implemented post a new answer functionality

---

client/src/components/RelatedItems/RelatedItemCard.jsx
client/src/context/questions/QuestionReducer.js
client/src/context/questions/QuestionState.js
helper.js
server.js

Updated Question and Answers Context
Question state updates when product is changed
Created a getanswers function with Questions context
Gets answers for specfic question id

Question and Answers Context

---

client/src/components/ProductOverview/product-image-gallery/product-image-gallery.component.jsx
client/src/components/ProductOverview/product-image-gallery/product-image-gallery.styles.scss
client/src/components/ProductOverview/product-style-selector/product-style-selector.styles.scss
client/src/components/RelatedItems/RelatedItemCard.jsx

Fixed issue with styles selector displaying more than 5 in a row
Corrected up and down arrows for thumbnail selector so that up arrow disappears when first item is selected and down arrow is hidden when last item in gallery is selected
Added functionality to relateditemcard to update questions when new product is updated

Style Selector and Thumbnail Gallery Fix, Questions Rerender on Product Change

---

client/src/components/RatingsAndReviews/RatingsData/RatingsData.jsx
client/src/components/RatingsAndReviews/Reviews/ReviewForm/FormPhotoViewer.jsx
client/src/components/RatingsAndReviews/Reviews/ReviewForm/ReviewForm.jsx
client/src/styles/base/_mixins.scss
client/src/styles/sections/RatingsAndReviews/RatingsData/_RatingsData.scss
client/src/styles/sections/RatingsAndReviews/Reviews/ReviewsForm/_FormPhotoViewer.scss
client/src/styles/sections/RatingsAndReviews/Reviews/ReviewsForm/_ReviewForm.scss
client/src/styles/sections/RatingsAndReviews/Reviews/ReviewsForm/_StarRater.scss
client/src/styles/sections/RatingsAndReviews/Reviews/_PhotoModal.scss
client/src/styles/sections/sharedComponents/_Voter.scss

- Changed position of elements within Review Form
- Elements no longer crowded
- redesigned tile remove photo display
BEFORE
https://user-images.githubusercontent.com/52953412/140746914-da205b31-7dd5-46dc-b5ea-66d47c6fc538.mp4
AFTER
https://user-images.githubusercontent.com/52953412/140746949-9236665d-0181-4b2b-8f14-39de6fe7efba.mp4

Review Form styling 

---

client/src/components/ProductOverview/product-navbar/product-navbar.component.jsx
client/src/components/QuestionsAndAnswers/AnswerForm.jsx
client/src/components/QuestionsAndAnswers/QuestionsAndAnswers.jsx
client/src/styles/components/_forms.scss
client/src/styles/sections/RatingsAndReviews/Reviews/ReviewsForm/_FormPhotoViewer.scss
client/src/styles/sections/_questions.scss

Fixed the photo upload modal window so it no longer closes the add answer modal
- changed class name prop passed to modal window component
Minor cosmetic changes
- added hover effect to add answer, report, found helpful answer and images
- added margin to questions main container
- changed id to questions-main-container
-
Changed the width and height properties as per Chris's request in reviews component

Minor cosmetic changes and fixed upload photo modal closing add answer

---

client/dist/bundle.js.LICENSE.txt
client/src/components/ProductOverview/ProductOverview.jsx
client/src/context/cart/CartState.js
client/src/context/products/ProductState.js
client/src/context/questions/QuestionState.js
client/src/context/reviews/ReviewState.js
jest.config.js
package-lock.json
package.json

Changed API calls from localhost:3000 to /api

Production setup

---

client/src/components/QuestionsAndAnswers/AnswerForm.jsx
client/src/components/QuestionsAndAnswers/QuestionForm.jsx
client/src/context/questions/QuestionState.js
client/src/spec/QuestionsAndAnswers/Questions.test.js
helper.js

Pull request after updating routs for AWS.

Cm testing2

---

client/src/components/QuestionsAndAnswers/QuestionItem.jsx
client/src/spec/QuestionsAndAnswers/Questions.test.js

also added a few enhancements to questions testing

Fixed localhost path to relative path

---

client/src/components/App.jsx
client/src/components/ProductOverview/ProductOverview.jsx

Set up React Lazy Loading for main components
Set up React lazy loading for Product Image Gallery and Expanded View Component as they had the largest contentful pain time
Reduced First Contenful Paint from 1.7s to 1.3ss
Reduct Largest Contentful Paint from 4.4s to 3.4s

React lazy loading

---

client/dist/index.html
client/src/components/ProductOverview/ProductOverview.jsx
client/src/components/ProductOverview/product-cart-modal/product-cart-modal.component.jsx
client/src/components/ProductOverview/product-dropdown/product-dropdown.component.jsx
client/src/components/ProductOverview/product-expanded-view/product-expanded-view.component.jsx
client/src/components/ProductOverview/product-image-gallery/product-image-gallery.component.jsx
client/src/components/ProductOverview/product-navbar/product-navbar.component.jsx
client/src/components/ProductOverview/product-social-media/product-social-media.component.jsx
client/src/components/ProductOverview/product-style-selector/product-style-selector.styles.scss
client/src/context/products/ProductState.js
helper.js
server.js

preloading font awesome
added alt attributes to images
deleted unneccesary console logs
deleted console logs in server
fixed styling on checkmark

Front end optimization

---

client/src/components/RelatedItems/OutfitCard.jsx
client/src/components/RelatedItems/OutfitSection.jsx
client/src/components/RelatedItems/RelatedItemCard.jsx
client/src/components/RelatedItems/RelatedItemsSection.jsx

remove code
